name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - development
  schedule:
    # See https://crontab.guru/weekly every sunday at 00:00
    - cron: 0 0 * * 0

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit